import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

const opensans = Open_Sans({
  weight: '400',
  subsets: ['latin'],
})
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={opensans.className}>{children}</body>
    </html>
  )
}
